import { StyleSheet } from "react-native";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../Helpers/Utilities/Utilities";

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    //justifyContent: "center",
  },
  leftImage: {
    height: getHeightEquivalent(15),
    width: getWidthEquivalent(18),
    marginRight: getWidthEquivalent(15),
  },
  optionsImage: {
    height: getHeightEquivalent(20),
    width: getWidthEquivalent(20),
    alignSelf: "flex-end",
  },
  headContainer: {
    height: getHeightEquivalent(24),
    width: getHeightEquivalent(382),
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: getHeightEquivalent(32),
  },
  headInContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  headText: {
    fontSize: fontEq(24),
    lineHeight: getHeightEquivalent(23.76),
    fontFamily: "Greycliffcf-demibold",
    color: "#000000",
  },
  billContainer: {
    height: getHeightEquivalent(48),
    width: getWidthEquivalent(382),
    backgroundColor: "#F2F6FF",
    flexDirection: "row",
    paddingLeft: getWidthEquivalent(16),
    //paddingVertical: getHeightEquivalent(16),
    marginTop: getHeightEquivalent(24),
    borderRadius: 8,
    elevation: 4,
    alignItems: "center",
  },
  billText1: {
    fontSize: fontEq(16),
    lineHeight: getHeightEquivalent(15.84),
    fontFamily: "Greycliffcf-demibold",
    color: "#123175",
    marginRight: getWidthEquivalent(8),
  },
  billText2: {
    fontSize: fontEq(16),
    lineHeight: getHeightEquivalent(15.84),
    fontFamily: "Greycliffcf-regular",
    color: "#606060",
  },
  dropdownButtonStyle: {
    width: getWidthEquivalent(70),
    height: getHeightEquivalent(40),
    backgroundColor: "#ffff",
    borderTopLeftRadius: 2,
    borderBottomLeftRadius: 2,
    borderRightWidth: 1,
    borderRightColor: "#E0E0E0",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(12),
  },
  flagSize: {
    height: getHeightEquivalent(16),
    width: getWidthEquivalent(22),
  },
  dropdownMenuStyle: {
    backgroundColor: `#ffffff`,
    borderRadius: 5,
    width: getWidthEquivalent(100),
  },
  dropdownItemStyle: {
    width: "100%",
    paddingHorizontal: getWidthEquivalent(12),
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(16),
  },
  tickIcon: { height: 10, width: 10, marginLeft: 5 },
  dropdown: {
    width: getWidthEquivalent(382),
    height: getHeightEquivalent(50),
    borderColor: "gray",
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },

  placeholderStyle: {
    fontSize: 14,
    width: 366,
    //height: 50,
    fontFamily: "Greycliffcf-regular",
    color: "#000000",
    verticalAlign: "middle",
    //borderWidth:1
  },
  dropDownContainer: {
    width: getWidthEquivalent(382),
    height: getHeightEquivalent(48),
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    paddingHorizontal: 10,
    marginTop: getHeightEquivalent(16),
  },
  selectedTextStyle: {
    fontSize: 16,
    color: "red",
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  changeContainer: {
    height: getHeightEquivalent(56),
    width: getWidthEquivalent(382),
    borderWidth: 1,
    borderColor: "#457B9D",
    borderRadius: 10,
    marginTop: getHeightEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  changeText: {
    fontSize: fontEq(16),
    lineHeight: getHeightEquivalent(15.84),
    fontFamily: "Greycliffcf-demibold",
    color: "#457B9D",
    alignSelf: "center",
  },
  partContainer: {
    height: getHeightEquivalent(19),
    width: getWidthEquivalent(382),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "center",
  },
  partText: {
    fontSize: fontEq(12),
    lineHeight: getHeightEquivalent(11.88),
    fontFamily: "Greycliffcf-medium",
    color: "#909090",
  },
  audioContainer: {
    height: getHeightEquivalent(56),
    width: getWidthEquivalent(382),
    elevation: 4,
    backgroundColor: "#ffffff",
    marginVertical: getHeightEquivalent(26),
    marginHorizontal: getWidthEquivalent(24),
    borderRadius: 8,
  },
  nameText: {
    fontSize: fontEq(12),
    lineHeight: getHeightEquivalent(14.4),
    fontFamily: "Greycliffcf-medium",
    color: "#909090",
  },
  messageBox: {
    width: getWidthEquivalent(366),
    borderWidth: 1,
    borderColor: "#D6D6D6",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: 10,
    marginTop: getHeightEquivalent(6),
  },
  messageText: {
    fontSize: fontEq(12),
    lineHeight: getHeightEquivalent(11.88),
    fontFamily: "Greycliffcf-medium",
    color: "#000000",
  },
  recordButton: {
    height: getHeightEquivalent(80),
    width: getHeightEquivalent(80),
    backgroundColor: "#E92F21",
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: getHeightEquivalent(63),
    elevation: 4,
    margin: getHeightEquivalent(10),
  },
  editButton: {
    height: getHeightEquivalent(48),
    width: getHeightEquivalent(48),
    backgroundColor: "#E3F4FF",
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: getHeightEquivalent(89),
    right: 62,
  },
});
