import { StyleSheet } from "react-native";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../Helpers/Utilities/Utilities";
export const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: "#00D09E",
    flex: 1,
  },
  subContainer1: {
    backgroundColor: "#00D09E",
    height: getHeightEquivalent(260),
    alignItems: "center",
    marginTop:getHeightEquivalent(60)
  },
  headContainer: {
    width: getWidthEquivalent(354),

    height: getHeightEquivalent(35),
    marginTop: getHeightEquivalent(28),
    marginLeft: getWidthEquivalent(38),
    marginRight: getWidthEquivalent(36),
    flexDirection: "row",
    justifyContent: "space-between",
  },
  headText1: {
    fontSize: fontEq(20),
    lineHeight: getHeightEquivalent(22),
    fontFamily: "poppins-semibold",
  },
  headText2: {
    fontSize: fontEq(14),
    //lineHeight: getHeightEquivalent(12.88),
    fontFamily: "poppins-regular",
  },
  notificationContainer: {
    height: getHeightEquivalent(30),
    width: getHeightEquivalent(30),
    backgroundColor: "#DFF7E2",
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  bodyContainer: {
    marginTop: getHeightEquivalent(41),
    flexDirection: "row",
  },
  bodyText1: {
    fontSize: fontEq(12),
    lineHeight: getHeightEquivalent(18),
    fontFamily: "poppins-regular",
    marginLeft: getWidthEquivalent(6),
  },
  balanceText: {
    fontSize: fontEq(24),
    lineHeight: getHeightEquivalent(36),
    fontFamily: "poppins-bold",
    color: "#F1FFF3",
  },
  divider: {
    height: getHeightEquivalent(42),
    borderColor: "#DFF7E2",
    borderWidth: 1,
    marginLeft: getWidthEquivalent(39),
    marginRight: getWidthEquivalent(33),
    alignSelf: "center",
  },
  progressContainer: {
    height: getHeightEquivalent(27),
    width: getWidthEquivalent(330),
    backgroundColor: "#052224",
    borderRadius: 13.5,
    marginTop: getHeightEquivalent(12),
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
  },
  progressText1: {
    fontSize: fontEq(12),
    fontFamily: "poppins-regular",
    color: "#F1FFF3",
    marginLeft: getWidthEquivalent(31),
  },
  inProgressContainer: {
    height: "100%",
    width: getWidthEquivalent(261),
    backgroundColor: "#F1FFF3",
    borderRadius: 13.5,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  progressText2: {
    fontSize: fontEq(13),
    fontFamily: "poppins-semibold",
    color: "#052224",
    marginRight: getWidthEquivalent(14),
  },
  descriptionText: {
    fontSize: fontEq(15),
    fontFamily: "poppins-regular",
    color: "#052224",
    marginLeft: getWidthEquivalent(10),
  },
  subContainer2: {
    flex: 1,
    backgroundColor: "#F1FFF3",
    borderRadius: 70,
    overflow: "hidden",
    paddingTop: getHeightEquivalent(33),
  },
  boardContainer: {
    height: getHeightEquivalent(152),
    width: getWidthEquivalent(357),
    backgroundColor: "#00D09E",
    borderRadius: 31,
    alignSelf: "center",
    // marginTop: getHeightEquivalent(33),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  inOneContainer: {
    width: getWidthEquivalent(63),
    alignSelf: "center",
  },
  inTwoContainer: {
    width: getWidthEquivalent(161),
  },
  boardText1: {
    fontSize: fontEq(12),
    fontFamily: "poppins-regular",
    color: "#052224",
  },
  boardText2: {
    fontSize: fontEq(12),
    fontFamily: "poppins-bold",
    color: "#052224",
  },
  boardDivider1: {
    borderTopWidth: 2,
    borderColor: "#F1FFF3",
    width: getWidthEquivalent(161),
    marginTop: getHeightEquivalent(11),
    marginBottom: getHeightEquivalent(13),
    alignSelf: "center",
    borderRadius: 20,
  },
  boardDivider2: {
    borderRightWidth: 2,
    borderColor: "#F1FFF3",
    height: getHeightEquivalent(108),
    borderRadius: 50,
    marginLeft: getWidthEquivalent(33.97),
    marginRight: getWidthEquivalent(18),
  },
  topNav: {
    height: getHeightEquivalent(60),
    width: getWidthEquivalent(358),
    backgroundColor: "#DFF7E2",
    borderRadius: 22,
    alignSelf: "center",
    marginTop: getHeightEquivalent(26),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(12.5),
  },
  inactiveTab: {
    height: getHeightEquivalent(31),

    width: getWidthEquivalent(95),
    alignItems: "center",
    justifyContent: "center",
  },
  activeTab: {
    width: getWidthEquivalent(95),
    height: getHeightEquivalent(50),
    backgroundColor: "#00D09E",
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  tabText: {
    fontSize: fontEq(15),
    fontFamily: "poppins-regular",
    color: "#052224",
    lineHeight: getHeightEquivalent(22.5),
  },
  cardContainer: {
    height: getHeightEquivalent(53),
    width: getWidthEquivalent(359),
    alignSelf: "center",
    marginTop: getHeightEquivalent(24),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logoContainer: {
    height: getHeightEquivalent(53),
    width: getWidthEquivalent(57),
    backgroundColor: "#0068FF",
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  cardText1: {
    fontSize: fontEq(15),
    fontFamily: "poppins-medium",
    color: "#052224",
  },
  cardText2: {
    fontSize: fontEq(12),
    fontFamily: "poppins-semibold",
    marginTop: getHeightEquivalent(2.35),
    lineHeight: getHeightEquivalent(18),
    color: "#0068FF",
  },
  cardDivider: {
    height: getHeightEquivalent(35.49),
    borderRightWidth: 1.01,
    borderColor: "#00D09E",
    alignSelf: "center",
    borderRadius: 50,
  },
  cardText3: {
    fontSize: fontEq(13),
    fontFamily: "poppins-medium",
    alignSelf: "center",
    color: "#052224",
  },
  cardText4: {
    fontSize: fontEq(15),
    fontFamily: "poppins-semibold",
    marginTop: getHeightEquivalent(2.35),
    alignSelf: "center",
  },
  progressContainer1: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },

  carIcon: {
    // Style your car icon here
    // For instance, you could use absolute positioning to center it within the progress circle
    position: "absolute",
  },
  progressText: {
    fontSize: fontEq(12),
    fontFamily: "poppins-semibold",
    color: "#093030",
    alignSelf: "center",
    marginTop: getHeightEquivalent(3.97),
  },
});
