import { StyleSheet } from "react-native";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../Helpers/Utilities/Utilities";
export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  headContainer: {
    height: getHeightEquivalent(56),
    width: getWidthEquivalent(375),
    flexDirection: "row",
    borderBottomWidth: 0.5,
    backgroundColor: "#ffffff",
    borderColor: "#D4DBE0",
    marginTop: getHeightEquivalent(15.7),
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(10),
  },
  header: {
    fontFamily: "PublicSans_600SemiBold",
    fontSize: fontEq(18),
    //lineHeight: getHeightEquivalent(21),
    color: "#294B67",
  },
  skipText: {
    fontFamily: "PublicSans_600SemiBold",
    fontSize: fontEq(15),
    //lineHeight: getHeightEquivalent(22.5),
    color: "#536F85",
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: "#F6F6F6",
  },
  textContainer: {
    width: getWidthEquivalent(335),
    alignSelf: "center",
    marginTop: getHeightEquivalent(30),
  },
  description: {
    fontFamily: "PublicSans_500Medium",
    fontSize: fontEq(16),
    lineHeight: getHeightEquivalent(24),
    color: "#294B67",
  },
  uploadContainer: {
    width: getWidthEquivalent(327),
    height: getHeightEquivalent(210.77),
    alignSelf: "center",
    marginTop: getHeightEquivalent(21.44),
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  uploadText: {
    fontFamily: "PublicSans_600SemiBold",
    fontSize: fontEq(20),
    lineHeight: getHeightEquivalent(23),
    color: "#294B67",
  },
  uploadButton: {
    width: getWidthEquivalent(170),
    height: getHeightEquivalent(48),
    alignSelf: "center",
    marginTop: getHeightEquivalent(20),
    borderRadius: 5,
    backgroundColor: "#E5665D",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontSize: fontEq(18),
    lineHeight: getHeightEquivalent(20),
    color: "#ffffff",
    fontFamily: "PublicSans_700Bold",
    marginLeft: getWidthEquivalent(6),
  },
  noteContainer: {
    width: getWidthEquivalent(327),
    height: getHeightEquivalent(45),
    alignSelf: "center",
    marginTop: getHeightEquivalent(20),
    backgroundColor: "#E7EEF0",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  noteText: {
    fontFamily: "PublicSans_600SemiBold",
    fontSize: fontEq(12),
    lineHeight: getHeightEquivalent(18),
    color: "#586E83",
    textAlign: "center",
  },
  text1: {
    fontFamily: "PublicSans_500Medium",
    fontSize: fontEq(16),
    lineHeight: getHeightEquivalent(24),
    color: "#586E83",
    marginTop: getHeightEquivalent(18),
    marginLeft: getWidthEquivalent(21),
  },
  tickContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: getWidthEquivalent(21),
    marginTop: getHeightEquivalent(8),
  },
  tickText: {
    fontFamily: "PublicSans_500Medium",
    fontSize: fontEq(12),
    lineHeight: getHeightEquivalent(18),
    color: "#586E83",
    marginLeft: getWidthEquivalent(6),
  },
  buttonContainer: {
    width: getWidthEquivalent(335),
    height: getHeightEquivalent(50.58),
    alignSelf: "center",
    marginTop: getHeightEquivalent(30),
    borderRadius: 5,
    backgroundColor: "#E5665D",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  continueText: {
    fontFamily: "PublicSans_700Bold",
    fontSize: fontEq(18),
    lineHeight: getHeightEquivalent(20),
    color: "#ffffff",
    marginRight: getWidthEquivalent(4),
  },
  buttonContainer2: {
    width: getWidthEquivalent(335),
    height: getHeightEquivalent(50.58),
    alignSelf: "center",
    marginTop: getHeightEquivalent(20),
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#E5665D",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: getHeightEquivalent(128),
  },
  stepText: {
    fontFamily: "PublicSans_700Bold",
    fontSize: fontEq(18),
    lineHeight: getHeightEquivalent(20),
    color: "#E5665D",
  },
  capturedImage: {
    width: "100%",
    height: 200,
    resizeMode:"contain",
    borderRadius: 10,
  },
});
