import { StyleSheet } from "react-native";
import {
  getHeightEquivalent,
  getWidthEquivalent,
  fontEq,
} from "../../Helpers/Utilities/Utilities";
import { height } from "../../Helpers/Constants/AppConstants";

export const styles = StyleSheet.create({
  mainContainer: {
    height: height,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  logo: {
    height: getHeightEquivalent(50),
    width: getWidthEquivalent(180.14),
    marginTop: getHeightEquivalent(43),
  },
  button: {
    backgroundColor: "#457B9D",
    height: getHeightEquivalent(48),
    width: getWidthEquivalent(366),
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(48),
  },
  whiteText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: "#00000",
    fontFamily: "Greycliffcf-demibold",
    lineHeight: getHeightEquivalent(15.84),
  },
  whiteButton: {
    backgroundColor: "#FFFFFF",
    height: getHeightEquivalent(48),
    width: getWidthEquivalent(366),
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: "#BFBFBF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(16),
  },
  titleContainer: {
    marginTop: getHeightEquivalent(49),
    height: getHeightEquivalent(32),
    width: "100%",
    marginBottom: getHeightEquivalent(48),
  },
  title: {
    fontSize: fontEq(32),
    lineHeight: getHeightEquivalent(31.68),
    fontFamily: "Greycliffcf-demibold",
    color: "black",
    alignSelf: "center",
    fontWeight: "600",
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ffffff",
    fontFamily: "Greycliffcf-demibold",
  },
  inputContainer: {
    height: getHeightEquivalent(74),
    width: getWidthEquivalent(366),
  },
  inTextContainer: {
    flexDirection: "row",
    marginBottom: getHeightEquivalent(12),
    justifyContent: "flex-start",
  },
  hash: {
    color: "red",
    fontSize: fontEq(14),
    fontWeight: "500",
  },
  inputText: {
    fontSize: fontEq(14),
    fontWeight: "500",
    fontFamily: "Greycliffcf-medium",
    color: "black",
    alignItems: "baseline",
    marginTop: getHeightEquivalent(3),
  },
  inputBox: {
    width: "100%",
    height: getHeightEquivalent(48),
    borderRadius: getHeightEquivalent(8.77),
    borderColor: "#E0E0E0",
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingLeft: getWidthEquivalent(16),
    flexDirection: "row",
  },
  textInput: {
    fontSize: fontEq(14),
    fontWeight: "400",
    fontFamily: "Greycliffcf-regular",
    height: "100%",
    color: "#C0C0C0",
    width: "100%",
  },
  eyeContainer: {
    height: getHeightEquivalent(20),
    width: getWidthEquivalent(20),
    marginVertical: getHeightEquivalent(14),
    marginRight: getWidthEquivalent(16),
  },
  forgotText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: "#5298C1",
  },
  bottomContainer: {
    flexDirection: "row",
    width: getWidthEquivalent(199),
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    alignSelf: "center",
    bottom: 0,
    marginBottom: getHeightEquivalent(37),
  },
  bottomText1: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: "#ff",
  },
  bottomText2: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: "#5298C1",
  },
});
