import { StyleSheet } from "react-native";
import {
  getHeightEquivalent,
  getWidthEquivalent,
  fontEq,
} from "../../Helpers/Utilities/Utilities";
export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  checkBox: {
    height: getHeightEquivalent(15),
    width: getHeightEquivalent(15),
    marginTop: getHeightEquivalent(4),
    marginRight: getWidthEquivalent(8),
    borderWidth: 0.75,
  },
  buttonWhiteText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: "#ffffff",
    fontFamily: "Greycliffcf-demibold",
    lineHeight: getHeightEquivalent(15.84),
  },
  whiteButton: {
    backgroundColor: "#ffff",
    height: getHeightEquivalent(48),
    width: getWidthEquivalent(366),
    borderWidth: 0.5,
    borderColor: "#BFBFBF",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(16),
  },
  whiteButtonText: {
    fontSize: fontEq(16),
    fontFamily: "Greycliffcf-demibold",
    color: "#000000",
  },
  nextButton: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ffffff",
    fontFamily: "Greycliffcf-demibold",
  },
  logo: {
    height: getHeightEquivalent(50),
    width: getWidthEquivalent(177.14),
    marginTop: getHeightEquivalent(43),
    alignSelf: "center",
  },
  titleContainer: {
    marginTop: getHeightEquivalent(49),
    height: getHeightEquivalent(32),
    width: "100%",
  },
  title: {
    fontSize: fontEq(32),
    lineHeight: getHeightEquivalent(31.68),
    color: "black",
    alignSelf: "center",
    fontFamily: "Greycliffcf-demibold",
  },
  inputContainer: {
    height: getHeightEquivalent(74),
    width: getWidthEquivalent(366),
    marginTop: getHeightEquivalent(24),
  },
  inTextContainer: {
    flexDirection: "row",
    marginBottom: getHeightEquivalent(12),
  },
  hash: {
    color: "red",
    fontSize: fontEq(14),
    fontWeight: "500",
  },
  inputText: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: "black",
    fontFamily: "Greycliffcf-medium",
    alignItems: "baseline",
    marginTop: getHeightEquivalent(3),
    lineHeight: getHeightEquivalent(16.8),
  },
  dropdownIcon: {
    width: 20,
    height: 20,
  },
  inputBox: {
    width: "100%",
    height: getHeightEquivalent(48),
    borderRadius: getHeightEquivalent(8.77),
    borderColor: "#E0E0E0",
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingLeft: getWidthEquivalent(12),
    flexDirection: "row",
  },
  textInput: {
    fontSize: fontEq(14),
    lineHeight: getHeightEquivalent(13.86),
    fontFamily: "Greycliffcf-regular",
    height: "100%",
    color: "black",
    width: "95%",
  },
  eyeContainer: {
    height: getHeightEquivalent(20),
    width: getWidthEquivalent(20),
    marginVertical: getHeightEquivalent(14),
    marginRight: getWidthEquivalent(16),
    marginLeft: getWidthEquivalent(16),
  },
  bottomContainer: {
    flexDirection: "row",
    width: getWidthEquivalent(199),
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: getHeightEquivalent(38),
    marginBottom: getHeightEquivalent(37),
  },
  bottomText1: {
    fontSize: fontEq(14),
    color: "#ff",
    lineHeight: getHeightEquivalent(24),
    fontFamily: "Greycliffcf-regular",
  },
  bottomText2: {
    fontSize: fontEq(14),
    lineHeight: getHeightEquivalent(13.86),
    color: "#5298C1",
    fontFamily: "Greycliffcf-demibold",
  },
  bottomText3: {
    fontSize: fontEq(14),
    fontWeight: "600",
    fontFamily: "Greycliffcf-demibold",
    color: "#2586CD",
  },
  dropdownButtonStyle: {
    width: getWidthEquivalent(70),
    height: getHeightEquivalent(40),
    backgroundColor: "#ffff",
    borderTopLeftRadius: 2,
    borderBottomLeftRadius: 2,
    borderRightWidth: 1,
    borderRightColor: "#E0E0E0",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(12),
  },
  flagSize: {
    height: getHeightEquivalent(16),
    width: getWidthEquivalent(22),
  },
  dropdownMenuStyle: {
    backgroundColor: `#ffffff`,
    borderRadius: 5,
    width: getWidthEquivalent(100),
  },
  dropdownItemStyle: {
    width: "100%",
    paddingHorizontal: getWidthEquivalent(12),
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(16),
  },
  tickIcon: { height: 10, width: 10, marginLeft: 5 },
  dropdown: {
    height: 50,
    borderColor: "gray",
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },

  placeholderStyle: {
    fontSize: 14,
    width: 366,
    height: 50,
    fontFamily: "Greycliffcf-regular",
    color: "#C0C0C0",
    verticalAlign: "middle",
  },
  selectedTextStyle: {
    fontSize: 16,
    color: "red",
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    width: 366,
    fontSize: 16,
  },
  stepperContainer: {
    height: getHeightEquivalent(54),
    width: getWidthEquivalent(238),
    marginTop: getHeightEquivalent(32),
    alignSelf: "center",
  },
  stepperInContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  progressContainer: {
    width: getWidthEquivalent(142),
    borderWidth: 2,
    position: "absolute",
    right: getWidthEquivalent(55),
    top: getHeightEquivalent(10),
  },
  activeContainer: {
    width: getWidthEquivalent(68),
    alignItems: "center",
    justifyContent: "space-between",
  },
  headText1: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: "#123175",
    fontFamily: "Greycliffcf-demibold",
    lineHeight: getHeightEquivalent(11.88),
  },
  inMainContainer: {
    width: getWidthEquivalent(88),
    height: getHeightEquivalent(54),
    alignItems: "center",
    justifyContent: "space-between",
  },
  pageHeader: {
    fontSize: fontEq(22),
    fontFamily: "Greycliffcf-demibold",
    alignSelf: "flex-start",
    marginTop: getHeightEquivalent(32),
    lineHeight: getHeightEquivalent(21.78),
  },
  dropDownContainer: {
    width: getWidthEquivalent(366),
    height: getHeightEquivalent(48),
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  button: {
    backgroundColor: "#457B9D",
    height: getHeightEquivalent(48),
    width: getWidthEquivalent(366),
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(32),
  },
  checkContainer: {
    height: getHeightEquivalent(48),
    width: getWidthEquivalent(366),
    marginTop: getHeightEquivalent(33),
    flexDirection: "row",
  },
});
